### ISSUE TITLE
Code Cleanup and Documentation

### ISSUE THREAD

**Issue by rmendels** [ptaconet/modisfast#10]
Please refer to this [JOSS review issue](https://github.com/openjournals/joss-reviews/issues/7343).

 I ran the present repository against devtools::check(), latest version, had one minor quibble with where the Citation was.  Also the tests fail when run this way,  because userid and password are required to access some of the data and of course you can't put that in a public repository.  But I did not see anything that would warn a user of this,  as well as instructions on how to run the tests since they will fail if trying to run automatically (note this is an item in the review checklist)  These could be comments in the test code.

Also ran the repository through the package 'goodpractice', I suggest the you should too. Clearly a lot of the items are individual taste. There were:

A lot of warnings about line length. Not a must but something the you might look at.
A lot of warnings about wanting a test for every single function. I have not looked yet to see if there is an adequate level of testing, but again something the you might look at.
A number of other suggestions about safe coding that perhaps should be looked at. There were really only a few, but they occurred in multiple places, so it generates a number of warnings.

**Comment by ptaconet** [comment]
Commit https://github.com/ptaconet/modisfast/commit/25c842b12e836fc358d42e00f2510faeaa2b8ff1  fixes the Citation problem

**Comment by ptaconet** [comment]
Commit https://github.com/ptaconet/modisfast/commit/b15397d275a813abf77e8702c03927996d8fe159 fixes part of the coding style suggestions. As suggested, I have ran the repository through the package 'goodpractice' (I did not know this package, thanks for the mention!). I have made the requested changes, except for the line length (I must say it is very difficult to respect the 80 characters line length...). For the functions testing, I am currently working on writing tests for the most important ones.

**Comment by ptaconet** [comment]
Commit https://github.com/ptaconet/modisfast/commit/e683529ba0e6d508c4d5f597d3f2933855b17bb6 adds tests for the main functions of the package, and documentation on how to execute them, as outlined in the Readme - see : https://github.com/ptaconet/modisfast/tree/master?tab=readme-ov-file#manual-testing-of-the-functionality

In addition, devtools::check() now does not fail anymore when running the package against devtools::check()

**Comment by V-Agudetse** [comment]
Hi @ptaconet, I have some feedback regarding the unit tests. Please let me know if you would prefer I open a separate issue for this, I will gladly do so.

1. Note: It is recommended, though not strictly necessary, that unit tests be structured in the same way as the files under R/; that is, one unit test per file/function. Among other things, this makes it easy to have a quick overview of which major functions are being tested and it also would allow you to check the level of testing coverage with a package like `covr`.
2. Arguments in unit tests should be explicitly named (e.g. `mf_login(credentials = c(earthdata_un, earthdata_pw))` rather than `mf_login(c(earthdata_un,earthdata_pw))`). This helps with readability and clarity but also makes the tests more robust in case new arguments are added to a function or the order of the arguments is changed. Line breaks would also be benefitial for readability.
3. This is more so a suggestion. Though some of the features do require credentials to be tested, there are others that could be tested without the use of credentials. For example, some of the sanity checks in mf_login() can be triggered by providing obviously invalid input: 
```
> mf_login(credentials = "hello")
Error in mf_login(credentials = "hello") : 
  credentials must be a vector character string of length 2 (username and password)
```
Adding these where possible and skipping only the tests that absolutely cannot run might allow for some degree of CI integration. [This testthat article](https://testthat.r-lib.org/articles/skipping.html#helpers) might be helpful. Also, in case it is useful, I see there are some tools available to test functions that use credentials or API requests: https://www.reddit.com/r/rstats/comments/n42yr4/how_to_handle_secret_data_in_unit_tests_of/?rdt=64315 

4. Some tests could be more extensive. For example, the tests for mf_list_collections() only checks that it is a data.frame, but there are no checks for the names and structure of the dataframe.

5. Failed tests after following the testing instructions:
```
── Failed tests ───────────────────────────────────────────────────────────────────────────────────────
Failure (test-modisfast.R:16:3): function mf_login() sends back the expected and outputs and errors when necessary
mf_login(c(earthdata_un, earthdata_pw)) is not NULL

`actual` is a character vector ('cli-8111-557')
`expected` is NULL

Failure (test-modisfast.R:207:3): modisfast works to download a GPM datacube
sum(res_dl$fileSize) not equal to 5689873.
1/1 mismatches
[1] 5564183 - 5689873 == -125690

[ FAIL 2 | WARN 283 | SKIP 0 | PASS 70 ]
```
Also, both the GPM datacube and the MODIS datacube raise several of these warnings on my laptop:
`GDAL Message 1: No UNIDATA NC_GLOBAL:Conventions attribute`. It seems like this might be related to the datasets and not a problem with modisfast/my installation but I have limited experience with GDAL so I am bringing it up just in case.

Cheers,

Victòria

**Comment by ptaconet** [comment]
Thanks a lot @V-Agudetse for both the bugs reports and suggestions, I will work on this very soon !

**Comment by ptaconet** [comment]
closing this issue as it was transferred to issue #15
